### ISSUE TITLE
Verificar en la solicitud los datos guardados en base

### ISSUE THREAD

**Issue by nicolasgarfinkiel** [nicolasgarfinkiel/Cresud.CDP#8]
Numero de Carta
FechaDeCarga
FechaDeVencimiento
IdCosecha
IdEspecie

Verificar con otras cartas. Los datos que son booleanos van como Null y no como 0 o 1

**Comment by pablozabo** [comment]
Pero ninguno de esos campos es bool....

**Comment by nicolasgarfinkiel** [comment]
Hace un select sobre la tabla. Recorda que el legacy no estaba bien.
